name: flutter_spell_checker
description: A Flutter plugin that enables spell-checking with suggestions based on device language settings. Ideal for real-time text validation in multilingual applications.
version: 1.0.0+1
homepage: https://calvinr.com
repository: https://github.com/celvinren/flutter_spell_checker
issue_tracker: https://github.com/celvinren/flutter_spell_checker/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_spell_checker
        pluginClass: FlutterSpellCheckerPlugin
      ios:
        pluginClass: FlutterSpellCheckerPlugin
